### PR TITLE
Create composer.json

### PR DESCRIPTION
**Pull request by sherakama**

### CODE REVIEW

**Review by pookmish — APPROVED** [review]

**Comment by pookmish** [comment]
How do we fix the admin role in travis issue?

**Comment by sherakama** [comment]
https://travis-ci.org/SU-SWS/stanford_jumpstart_academic/builds/339333466#L1931

Connection timeouts ... 

Kellie might know something about this.

**Comment by pookmish** [comment]
Same error on https://travis-ci.org/SU-SWS/stanford_courses/builds/339560268#L2036

**Comment by pookmish** [comment]
Create composer.json

**Pull request merged**
